# Generated by Django 5.0.7 on 2024-08-14 15:01

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_short_description_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/products/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/seller/categories/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/side'),
        ),
        migrations.CreateModel(
            name='CategoriesAdmin',
            fields=[
                ('id', models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/admin/categories/')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categoriesadmin')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categoriesadmin'),
        ),
    ]
