# Generated by Django 5.0.6 on 2024-06-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_seller_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.RemoveField(
            model_name='store',
            name='customers',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
