# Generated by Django 5.0.6 on 2024-07-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_address_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='stock',
        ),
    ]
