# Generated by Django 5.0.7 on 2024-08-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_productcategory_isadmin_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='isadmin',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='store',
        ),
        migrations.DeleteModel(
            name='CategoriesAdmin',
        ),
    ]
