# Generated by Django 5.0.6 on 2024-06-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_store_seller_alter_stock_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AddField(
            model_name='store',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.address'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='variation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.variationoption'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='attribute_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productcategory'),
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='option_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.variation'),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
