# Generated by Django 5.0.6 on 2024-07-01 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_shoppingcartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporder',
            name='order_status',
        ),
        migrations.AddField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('delivered', 'devilered')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AlterField(
            model_name='store',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stock'),
        ),
        migrations.CreateModel(
            name='draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.store')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.store')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
