# Generated by Django 5.0.7 on 2024-07-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_store_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
