# Generated by Django 5.0.7 on 2024-08-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_productcategory_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
