# Generated by Django 5.0.7 on 2024-08-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='variation_options',
            field=models.ManyToManyField(related_name='product_variations', to='base.variations'),
        ),
    ]
