# Generated by Django 5.0.7 on 2024-08-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_productcategory_store_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='variation',
            new_name='product_item_variation',
        ),
    ]
