# Generated by Django 5.0.7 on 2024-07-29 02:25

import base.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerlist',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='draft',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotioncategory',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publish',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variation',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='id',
            field=models.UUIDField(default=base.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
