# Generated by Django 5.0.6 on 2024-07-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_shoporder_order_status_shoporder_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='order_total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('delivered', 'delivered')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
