# Generated by Django 5.0.7 on 2024-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_variation_stock_product_item_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='variation_options',
            field=models.ManyToManyField(related_name='product_variations', to='base.variationoption'),
        ),
    ]
