# Generated by Django 5.0.7 on 2024-07-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_address_users_alter_store_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='unit_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
