# Generated by Django 5.0.6 on 2024-07-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_category_alter_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
