# Generated by Django 5.0.7 on 2024-07-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_users_address_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line1',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line2',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='unit_number',
            new_name='village',
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
