# Generated by Django 5.0.7 on 2024-08-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='review_text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='order_product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
