# Generated by Django 5.0.6 on 2024-07-02 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_address_address_line1_alter_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='seller',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, through='base.PromotionCategory', to='base.productcategory'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shippingmethod'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orderline'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
    ]
